import type {
  AtBatResult,
  Position,
} from "../../src/generated/prisma/client.js";

type PlateAppearanceData = {
  gameMemberId: number;
  inningNumber: number;
  atBatInGame: number;
  result: AtBatResult;
  direction: Position | null;
  rbi: number;
};

// 試合1: PlateAppearance（DH制、5回ビッグイニング含む）
// 5回: 7番鈴木が3打席、他8名が2打席（打順が約2.5周）
export function getGame1PAs(
  gameMembers: { id: number }[],
): PlateAppearanceData[] {
  return [
    // 1番 中村翔（中）: 5打席 — 左安, 中安(1), 右二(2), 右安(1), 左飛
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "single",
      direction: "left",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "single",
      direction: "center",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "double",
      direction: "right",
      rbi: 2,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "single",
      direction: "right",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 6,
      atBatInGame: 5,
      result: "flyOut",
      direction: "left",
      rbi: 0,
    },
    // 2番 伊藤誠（遊）: 5打席 — 遊ゴロ, 左飛, 左安(1), 四球, 遊ゴロ
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "flyOut",
      direction: "left",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "single",
      direction: "left",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 7,
      atBatInGame: 5,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    // 3番 佐藤一郎（一）: 5打席 — 右安(1), 三振, 左本(2), 中安(1), 右飛
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "single",
      direction: "right",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "homeRun",
      direction: "left",
      rbi: 2,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "single",
      direction: "center",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 7,
      atBatInGame: 5,
      result: "flyOut",
      direction: "right",
      rbi: 0,
    },
    // 4番 高橋健（三）: 5打席 — 併殺, 遊ゴロ, 四球, 左安(1), 三振
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "doublePlay",
      direction: "second",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "single",
      direction: "left",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 7,
      atBatInGame: 5,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    // 5番 渡辺大輔（左）: 4打席 — 三振, 右飛, 中安, 右安(1)
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "flyOut",
      direction: "right",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "single",
      direction: "center",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "single",
      direction: "right",
      rbi: 1,
    },
    // 6番 松本涼介（DH）: 4打席 — 中飛, 三振, 右二(1), 三振
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "flyOut",
      direction: "center",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "double",
      direction: "right",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    // 7番 鈴木雪（二）: 4打席 — 投ゴロ, 左安, 犠飛(1), 遊ゴロ ※5回に3打席
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "groundOut",
      direction: "pitcher",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "single",
      direction: "left",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "sacrificeFly",
      direction: "center",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 5,
      atBatInGame: 4,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    // 8番 山田花子（捕）: 4打席 — 四球, 右安, 四球, 遊ゴロ
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "single",
      direction: "right",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 6,
      atBatInGame: 4,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    // 9番 小林勇気（右）: 4打席 — 犠打, 中安(1), 左安(1), 三振
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "sacrificeHit",
      direction: "pitcher",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "single",
      direction: "center",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "single",
      direction: "left",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 6,
      atBatInGame: 4,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    // 10番 田中太郎（投）: DH制のため打席なし
  ];
}

// 試合2: PlateAppearance（各スタメン3打席、9番のみ2打席）
export function getGame2PAs(
  gameMembers: { id: number }[],
): PlateAppearanceData[] {
  return [
    // 1番 田中太郎（中）: 遊ゴロ, 三振, 中飛
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 6,
      atBatInGame: 3,
      result: "flyOut",
      direction: "center",
      rbi: 0,
    },
    // 2番 山田花子（遊）: 三振, 左安, 遊ゴロ
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "single",
      direction: "left",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 6,
      atBatInGame: 3,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    // 3番 佐藤一郎（一）: 右飛, 中安(1), 三振
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "flyOut",
      direction: "right",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "single",
      direction: "center",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 7,
      atBatInGame: 3,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    // 4番 鈴木雪（三）: 三振, 二ゴロ, 右安(1)
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "groundOut",
      direction: "second",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 7,
      atBatInGame: 3,
      result: "single",
      direction: "right",
      rbi: 1,
    },
    // 5番 高橋健（左）: 左飛, 三振, 四球
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "flyOut",
      direction: "left",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 7,
      atBatInGame: 3,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    // 6番 伊藤誠（右）: 遊ゴロ, 三振, 右飛
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 7,
      atBatInGame: 3,
      result: "flyOut",
      direction: "right",
      rbi: 0,
    },
    // 7番 渡辺大輔（二）: 三振, 一ゴロ, 中飛
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "groundOut",
      direction: "first",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 7,
      atBatInGame: 3,
      result: "flyOut",
      direction: "center",
      rbi: 0,
    },
    // 8番 中村翔（捕）: 投ゴロ, 四球, 三振
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "groundOut",
      direction: "pitcher",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 7,
      atBatInGame: 3,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    // 9番 小林勇気（投）: 三振, 遊ゴロ
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 6,
      atBatInGame: 2,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
  ];
}

// 試合3: PlateAppearance（5イニング、各スタメン2-3打席）
export function getGame3PAs(
  gameMembers: { id: number }[],
): PlateAppearanceData[] {
  return [
    // 1番 田中太郎（中）: 左安(1), 中飛, 右安
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "single",
      direction: "left",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "flyOut",
      direction: "center",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[0].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "single",
      direction: "right",
      rbi: 0,
    },
    // 2番 山田花子（遊）: 四球, 遊ゴロ, 左安
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "walk",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[1].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "single",
      direction: "left",
      rbi: 0,
    },
    // 3番 佐藤一郎（一）: 右二(1), 三振, 中本(1)
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "double",
      direction: "right",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[2].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "homeRun",
      direction: "center",
      rbi: 1,
    },
    // 4番 鈴木雪（三）: 中飛, 左安(1), 三振
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 1,
      atBatInGame: 1,
      result: "flyOut",
      direction: "center",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 3,
      atBatInGame: 2,
      result: "single",
      direction: "left",
      rbi: 1,
    },
    {
      gameMemberId: gameMembers[3].id,
      inningNumber: 5,
      atBatInGame: 3,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    // 5番 高橋健（左）: 三振, 投ゴロ
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[4].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "groundOut",
      direction: "pitcher",
      rbi: 0,
    },
    // 6番 伊藤誠（右）: 右飛, 死球
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "flyOut",
      direction: "right",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[5].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "hitByPitch",
      direction: null,
      rbi: 0,
    },
    // 7番 渡辺大輔（二）: 遊ゴロ, 中安
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 2,
      atBatInGame: 1,
      result: "groundOut",
      direction: "shortstop",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[6].id,
      inningNumber: 4,
      atBatInGame: 2,
      result: "single",
      direction: "center",
      rbi: 0,
    },
    // 8番 中村翔（捕）: 三振, 犠打
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[7].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "sacrificeHit",
      direction: "pitcher",
      rbi: 0,
    },
    // 9番 小林勇気（投）: 投ゴロ, 三振
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 3,
      atBatInGame: 1,
      result: "groundOut",
      direction: "pitcher",
      rbi: 0,
    },
    {
      gameMemberId: gameMembers[8].id,
      inningNumber: 5,
      atBatInGame: 2,
      result: "strikeout",
      direction: null,
      rbi: 0,
    },
  ];
}
